site_name: Cookiecutter Data Science at IKNL
site_description: Cookiecutter template for Data Science projects at IKNL.
site_favicon: favicon.ico
repo_url: https://github.com/arturomoncadatorres/cookiecutter-data-science-iknl
copyright: Originally based on the template by Sven van der Burg.
google_analytics: ['UA-54096005-4', 'auto']
theme: cinder
extra_css:
  - css/extra.css
pages:
  - Home: index.md
